# ---------------------
# portfolio section

projects:
- {name: One Up King, folder: 'proj-1'}
- {name: NausDesign re-branding, folder: 'proj-2'}
- {name: Military Patch work, folder: 'proj-3'}
- {name: SongKane.com, folder: 'proj-4'}